source 'http://rubygems.org'

gem 'capybara'
gem 'chromedriver-helper'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'rspec'
gem 'rubocop'
gem 'fastri'
gem 'rcodetools'
gem'httparty'
gem'faker'
gem'ffaker'
gem 'site_prism'
gem 'pry'